// <auto-generated />
using System;
using CinemaApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CinemaApp.Migrations
{
    [DbContext(typeof(CinemaDbContext))]
    [Migration("20200806143108_Version2")]
    partial class Version2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CinemaApp.Models.Booking", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TimeSlotID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TimeSlotID");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("CinemaApp.Models.CinemaRoom", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RoomNr")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("CinemaRooms");
                });

            modelBuilder.Entity("CinemaApp.Models.Movie", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("CoverPhoto")
                        .HasColumnName("CoverPhoto")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Description")
                        .HasColumnName("Description")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Duration")
                        .HasColumnName("Duration")
                        .HasColumnType("varchar(250)");

                    b.Property<double>("Rating")
                        .HasColumnName("Rating")
                        .HasColumnType("float");

                    b.Property<DateTime>("ReleasedDate")
                        .HasColumnName("Release Data")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .HasColumnName("Title")
                        .HasColumnType("varchar(250)");

                    b.HasKey("ID");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("CinemaApp.Models.Seat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BookingID")
                        .HasColumnType("int");

                    b.Property<int?>("CinemaRoomID")
                        .HasColumnType("int");

                    b.Property<int>("Nr")
                        .HasColumnType("int");

                    b.Property<string>("Row")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("ID");

                    b.HasIndex("BookingID");

                    b.HasIndex("CinemaRoomID");

                    b.ToTable("Seat");
                });

            modelBuilder.Entity("CinemaApp.Models.TimeSlot", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CinemaRoomID")
                        .HasColumnType("int");

                    b.Property<string>("MovieID")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("CinemaRoomID");

                    b.HasIndex("MovieID");

                    b.ToTable("TimeSlots");
                });

            modelBuilder.Entity("CinemaApp.Models.Booking", b =>
                {
                    b.HasOne("CinemaApp.Models.TimeSlot", "TimeSlot")
                        .WithMany()
                        .HasForeignKey("TimeSlotID");
                });

            modelBuilder.Entity("CinemaApp.Models.Seat", b =>
                {
                    b.HasOne("CinemaApp.Models.Booking", null)
                        .WithMany("Seats")
                        .HasForeignKey("BookingID");

                    b.HasOne("CinemaApp.Models.CinemaRoom", null)
                        .WithMany("Seats")
                        .HasForeignKey("CinemaRoomID");
                });

            modelBuilder.Entity("CinemaApp.Models.TimeSlot", b =>
                {
                    b.HasOne("CinemaApp.Models.CinemaRoom", "CinemaRoom")
                        .WithMany()
                        .HasForeignKey("CinemaRoomID");

                    b.HasOne("CinemaApp.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieID");
                });
#pragma warning restore 612, 618
        }
    }
}
